# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(763, 555)
        Dialog.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widgetDendrogram = QtWidgets.QWidget(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widgetDendrogram.sizePolicy().hasHeightForWidth())
        self.widgetDendrogram.setSizePolicy(sizePolicy)
        self.widgetDendrogram.setObjectName("widgetDendrogram")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widgetDendrogram)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.widgetDendrogram)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setStyleSheet("padding: 8px 10px 7px 10px;\n"
"background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #ffffff, stop:1 #e0e0e0);\n"
"border: 1px solid #b8b8b8;\n"
"border-bottom: 0px;")
        self.label_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.frameDendrogram = QtWidgets.QFrame(self.widgetDendrogram)
        self.frameDendrogram.setStyleSheet("background-color: #ffffff;")
        self.frameDendrogram.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameDendrogram.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameDendrogram.setObjectName("frameDendrogram")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frameDendrogram)
        self.verticalLayout_6.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_2.addWidget(self.frameDendrogram)
        self.verticalLayout.addWidget(self.widgetDendrogram)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dendrogram"))
        self.label_5.setText(_translate("Dialog", "<html><head/><body><p>Dendrogram <span style=\" font-size:9pt;\">(click to adjust clustering threshold)</span></p></body></html>"))
